### ISSUE TITLE
SDLF DDK MWAA pipeline orchestration

### ISSUE THREAD

**Issue by anmolsgandhi** [aws-samples/aws-ddk-examples#54]

**Comment by devansh-gandhi** [comment]
Hi, 

I am interested in taking on this issue. I have experience working with DDK and sdlf-ddk-lightweight on a project and have recently designed a pipeline using MWAATriggerDagsStage in a simillar usecase. Since I am new in contributing to open source, I would greatly appreciate some guidance along the way. Looking forward to collaborating!

**Comment by anmolsgandhi** [comment]
Thanks for your interest in working on this issue @devansh-gandhi. Please let us know what do you have in mind. We'd like to make it as generic as possible to align with the framework in general. Please open a PR when you are ready!

**Comment by devansh-gandhi** [comment]
Hi @anmolsgandhi, I wanted to share some updates on the progress. 

These are the proposed design changes I am considering to implement the sdlf-ddk-lightweight with MWAA orchestration – 

A new parameter will be added to the parameters.json to determine the orchestration type (SFN/ MWAA). If the parameter is set to SFN, the existing pipeline stages will be deployed. However, when it is set to MWAA, a MWAATriggerDagsStage and MWAAEnvironment will be deployed instead of the stage-a and stage-b step functions. New Stage-a and stage-b airflow dags will be created to trigger their corresponding lambda functions.  

The following changes will be implemented in the current pipeline structure - 

1) In routing-a lambda function, the event will now be passed to the step function as a dict instead of string
2) Within the SDLFLightTransform stack, the creation the lambda functions is decoupled from creation of the step function tasks. This seperation enables the lambda functions to be created independently for the MWAA orchestration and prevents unnecessary creation of the step function task. 
3) Conditional statements will be added to prevent extra resources from being created

Note: I am planning to use the same parameter values for the step functions(stage-a/stage-b). Depending on the orchestration it will trigger the sfn or dag respectively.   

Process flow- 
When an object is created in S3 raw bucket, it routes to the ‘routing-a’ lambda function. The 'routing-a' function adds a ‘dag_ids’ field to the event and initiates the MWAATriggerDagsStage step function.The MWAATriggerDagsStage step function then transfers the entire event to the stage-a airflow dag. The stage-a dag proceeds to invoke the stage-a lambda functions and successfully completes its execution. Similiarly, the stage-b routing lambda triggers the execution of the stage-b mwaa dag. 

Please let me know if this looks good. 

I am planning to open a draft pr soon.

**Comment by devansh-gandhi** [comment]
Hi Anmol, Thank you for your reply. I have been working on the Stage B and creating separate MWAA environments for each team. While working on the latter, I faced an error, so I have opened a issue/pr on aws-ddk for the same. I will be ready to share my updates and open a pr here soon after that issue is resolved.
